### ISSUE TITLE
integrate blockchain explorer into bestchain

### ISSUE THREAD

**Issue by bjwswang** [bestchains/fabric-operator#130]

**Comment by Abirdcfly** [comment]
Is this a front-end task? Should we need blockchain to use our u4a certification? 😯

**Comment by bjwswang** [comment]
> Is this a front-end task? Should we need blockchain to use our u4a certification? 😯

  we need to confirm this  explorer can work with our network. and for sure front end should integrate this with IAM.

**Comment by bjwswang** [comment]
move this task to https://github.com/bestchains/bc-explorer
