### ISSUE TITLE
copy federation member list into network

### ISSUE THREAD

**Issue by bjwswang** [bestchains/fabric-operator#143]

**Comment by 0xff-dev** [comment]
目前改动两种方式
- 直接删除network的members字段，然后所有对member的获取都从federation来。
- 修改fedration controller的network的watch逻辑。当federation的member发生变化的时候，同步到network，这样需要每个network添加一个federation的label。当network更新的时候，也要与federation对比。

1.  方案1
删除member字段，会涉及到一些函数的改动，需要添加client，用来获取federation的member信息。改动量目测比较大。

2. 方案2
在fedeartion的controller中有对networkd的watch逻辑。federation是优先于network创建的。当network创建的时候，通过federation字段判断member是否一致。当network更新的时候，也要与federation对比。如果不一致，按照federation的来。

如果federation更新，则需要根据network的label筛选，将所有的network更新一遍。

network创建的时候需要添加federation的label。

**Comment by 0xff-dev** [comment]
## 实现逻辑

方案是让网络同步联盟的members.

- 联盟删除成员
如果联盟删除成员，会发起proposal，`通过proposal webhook 判断删除的成员是否是某个网络的发起者，或者channel的成员`。如果是则不允许删除

- 联盟添加成员
联盟添加成员，需要将这个成员同步到联盟下的所有网络

- network的webhook
network需要在network创建，更新的时候判断members是否与联盟的一致，不一致，不允许后续的逻辑。

- network合并联盟的members
保留network原始数据的属性，将联盟新增的append到后面，或者移除。不要直接复制，避免，发起者，JoinedBy等字段丢失。
