### ISSUE TITLE
optimize User's annotations

### ISSUE THREAD

**Issue by bjwswang** [bestchains/fabric-operator#15]
1. merge  admin/peers/orderers together under the field `IDs`
2. move Admin's attributes under `ID.attibutes`

So overall Annotation will be 
```

const BlockchainAnnotationKey = "bestchains"

type BlockchainAnnotation struct {
	// Organization info
	Organization string `json:"organization,omitempty"`
	Namespace    string `json:"namespace,omitempty"`

       // IDs under current User's management
	IDs map[string]ID `json:"ids,omitempty"`
}

type ID struct {
	Name         string            `json:"name"`
	Type         string            `json:"type"`
	Attributes   map[string]string `json:"attributes"`
	CreationTime string            `json:"creationTime"`
}

type BlockchainAnnotationList struct {
	List            map[string]BlockchainAnnotation `json:"list,omitempty"`
	LastAppliedTime string                          `json:"lastAppliedTime,omitempty"`
	LastDeleteTime  string                          `json:"lastDeleteTime,omitempty"`
}

```
`Attributes` will contain:
```
	// Enrollment
	// EnrollmentID           string `json:"hf.EnrollmentID,omitempty"`
	// Type                   string `json:"hf.Type,omitempty"`
	// Affiliation            string `json:"hf.Affiliation,omitempty"`
	// RegistrarRoles         string `json:"hf.Registrar.Roles,omitempty"`
	// RegistrarDelegateRoles string `json:"hf.Registrar.DelegateRoles,omitempty"`
	// Revoker                string `json:"hf.Revoker,omitempty"`
	// IntermediateCA         string `json:"hf.IntermediateCA,omitempty"`
	// GenCRL                 string `json:"hf.GenCRL,omitempty"`
	// RegistrarAttributes    string `json:"hf.Registrar.Attributes,omitempty"`
```

ID's management will be like this:
1. When User create a organization,add `ID` with type `admin` for this User
2. When organization's Admin transfered to another User,   
      - move `list.org` to new User's annotation  
      - set new user's ID type to `admin`  
      - set old User's ID type to `client`  
3. When a `User` is granted `Client` under this organization,
      - add a new ID with type `client` in Admin's annotation
      - add this ID in its own annotation
4. When deploy `IBPPeer` or `IBPOrderer`, add a new ID with type `peer/orderer`
5. When delete `IBPPeer` or `IBPOrderer`,delete the relevant ID

**Comment by bjwswang** [comment]
@0xff-dev @Abirdcfly @nkwangleiGIT  Please leave comments here.  This optimization will help a lot when list ids under this CA


![Image](https://user-images.githubusercontent.com/30621793/208855878-8540b70b-f692-42f1-b684-63fb27b4d792.png)

**Comment by bjwswang** [comment]
@0xff-dev Are there any fields which are required by IAM/enroll/revoke but missing in the design struct?

**Comment by 0xff-dev** [comment]
At present I think the fields are sufficient, in the user annotations have peer or order id, and then enroll, according to the request header peerid and user annotations to do a comparison, and then for peer or order to return a fake user, and finally generate the relevant certificate.

**Comment by bjwswang** [comment]
@0xff-dev 
```json
{
    "list":{
        "org1":{
            "organization":"org1",
            "namespace":"org1",
            "ids":{
                "org1admin":{
                    "name":"org1admin",
                    "type":"admin",
                    "attributes":{
                        "hf.Affiliation":"",
                        "hf.EnrollmentID":"org1admin",
                        "hf.GenCRL":"true",
                        "hf.IntermediateCA":"true",
                        "hf.Registrar.Roles":"*",
                        "hf.RegistrarDelegateRoles":"*",
                        "hf.Revoker":"*",
                        "hf.Type":"admin",
                        "hf.hf.Registrar.Attributes":"*"
                    },
                    "creationTime":"2022-12-22 14:34:00.681636 +0800 CST m=+135.544195580"
                }
            }
        }
    },
    "lastAppliedTime":"2022-12-22 14:34:00.681644 +0800 CST m=+135.544203511"
}
```

**Comment by bjwswang** [comment]
https://github.com/bestchains/fabric-operator/pull/17
