### ISSUE TITLE
use chaincodeBuildReference in Chaincde deployment

### ISSUE THREAD

**Issue by bjwswang** [bestchains/fabric-operator#160]

**Comment by 0xff-dev** [comment]
chaincode使用字段`ExternalBuilder`字段记录`ChaincodeBuilder`的名字。

### 安装chaincode
- 用户创建 Proposal，proposal中带着chaincodebuild的名字。
- 当 Proposal 通过后，operator 将 chaincodebuild的名字和镜像信息更新到chaincode这个CR中。
- 走后面的安装逻辑

### 升级 chaincode
- 用户创建升级的Proposal 也是需要带着chaincodebuild的名字。
- 当Proposal通过后，operator将chaincode的名字和镜像信息更新到chaincode的CR中，并且在history中记录一条历史镜像信息。
- 通过后，走升级安装逻辑。

### 改动
原来的Proposal  spec.DeployChaincode部署定义调整为
```diff
- type DeployChaincodeProposal struct {
-	Chaincode string   `json:"chaincode"`
-	Members   []Member `json:"members"`
- }

+ type DeployChaincodeProposal struct {
+      ExternalBuilder string `json:"externalBuilder"`
+      Chaincode string `json:"chaincode"`
+      Members []Member 
+ }
```
