### ISSUE TITLE
add channel id field for Channel

### ISSUE THREAD

**Issue by bjwswang** [bestchains/fabric-operator#189]
add a field `ID` for `Channel` which indicates the real channel id in blockchain network.

keep `metadat.name` in 
- conneciton profile's configmap name
- rbac

use `channel.spec.id` filed in 
- channel creation
- channel join
- chaincode deployment

**Comment by 0xff-dev** [comment]
- 创建channel，需要填写id字段。
- 字段不可以更新。
- peer假如channel需要写id
- chaincode部署的channel需要写id。
