### ISSUE TITLE
optimize chaincode build to accelerate build pipeline

### ISSUE THREAD

**Issue by bjwswang** [bestchains/fabric-operator#221]
now CCB takes 4minutes or more to finish the image build process which is too long.

**Comment by Lanture1064** [comment]
Unpacking rootfs as cmd ADD . $GOPATH/go-contract requires it. 109s
第一次 filesystem 快照 39s
Running: [/bin/sh -c go build -ldflags="-X main.version=0.0.1" -o /go/bin/go-contract ${PACKAGE}]  272s
第二次 filesystem 快照 61s
Unpacking rootfs as cmd COPY --from=build /usr/bin/dumb-init /usr/bin/dumb-init requires it. 103s
