### ISSUE TITLE
when chaincode phase will be Committed ? 

### ISSUE THREAD

**Issue by bjwswang** [bestchains/fabric-operator#233]
when chaincode got committed ,its `phase` should be `Committed`.right?

but what i observed is `committed` never patched

![image](https://user-images.githubusercontent.com/30621793/230834011-95be50ec-d12a-4b64-bab1-427d6ae071de.png)

@0xff-dev next stage is `Running` but now is `Approved`?

**Comment by bjwswang** [comment]
@0xff-dev When chaincode got committed, we should allow chaincode upgrade even pod is not runnig

**Comment by 0xff-dev** [comment]
`status.phase` indicates that the current chaincode is allowed to be installed.
`nextStage` indicates the stage to be executed if the processing fails at that time.
Only when the pod of chaincode is up will status.phase change to running.

**Comment by bjwswang** [comment]
before chaincode running ,the current stage whould be `Committed`,right ?

**Comment by 0xff-dev** [comment]
When the chaincode is not running, if it has been committed it is possible to do an upgrade.
