### ISSUE TITLE
Support to choose a different version of Fabric

### ISSUE THREAD

**Issue by massimo-romano** [bestchains/fabric-operator#250]
Hello, is there any way to select a different version of Fabric?
In particular I'm interested in the 2.2.x LTS series.

I tried to edit the samples-network/network file by setting:
`context FABRIC_VERSION 2.2.9`

and replacing the corresponding binaries in samples-network/bin, but during the **network cluster init** I get this response:

`Error response from daemon: manifest for hyperledgerk8s/fabric-peer:2.2.9 not found: manifest unknown: manifest unknown
`
Of course, the information for this version is missing. Is it possible to add it somehow?

I am using on an Ubuntu 20.04 machine a Rancher/k3s installation configured with Kubernetes v1.24.8, dockerd (moby) enabled and Traefik disabled.

Thank you,

**Comment by bjwswang** [comment]
> Hello, is there any way to select a different version of Fabric? In particular I'm interested in the 2.2.x LTS series.
> 
> I tried to edit the samples-network/network file by setting: `context FABRIC_VERSION 2.2.9`
> 
> and replacing the corresponding binaries in samples-network/bin, but during the **network cluster init** I get this response:
> 
> `Error response from daemon: manifest for hyperledgerk8s/fabric-peer:2.2.9 not found: manifest unknown: manifest unknown ` Of course, the information for this version is missing. Is it possible to add it somehow?
> 
> I am using on an Ubuntu 20.04 machine a Rancher/k3s installation configured with Kubernetes v1.24.8, dockerd (moby) enabled and Traefik disabled.
> 
> Thank you,

Hi @massimo-romano .  Can you pls tell why you choose 2.2.x LTS version?  `bestchains` here provides a one-stop blockchain solution upon kubernets for productiuon ready use case.  We use 2.4.x by default. 

This opperator originally comes from hyyperledger-labs but we have done lots of work towards federation/channels/chaincode management/optimization. 

You can have a try by using this installer https://github.com/bestchains/installer 

Once again,thanks you for paying attention on our project! And  feel free to let me know if you have any other  questions

**Comment by massimo-romano** [comment]
Hi @bjwswang , thank you for your response.

I'm forced to use a 2.2.x version of Fabric because we have already developed a Spring Eureka application that interacts with this version of the network (at the time the latest LTS available) and our application is not immediately compatible with later versions. The current production system is implemented via docker (pure networking, no swarm) and is running on separate machines but we have just been asked to move it to Kubernetes.

Your project is interesting so I will try the installer anyway even though I won't be able to use it for this specific version of Fabric.
