### ISSUE TITLE
more labels on CRDs to make selection more efficient

### ISSUE THREAD

**Issue by bjwswang** [bestchains/fabric-operator#32]

**Comment by bjwswang** [comment]
CRD User

- "bestchains.organization.{org_name}": {roletype}

**Comment by bjwswang** [comment]
CRD Proposal
- `bestchains.proposal.type: ""`  标记当前proposal的类型

**Comment by bjwswang** [comment]
CRD Organizaiton
- `bestchains.federation.initiator: {org_name}` 标记当前联盟的发起者

**Comment by bjwswang** [comment]
CRD Federation
- [ ] `bestchains.federation.initiator: {org_name}` 标记当前联盟的发起者

**Comment by bjwswang** [comment]
CRD Network

- [ ] `bestchains.network.initiator: {org_name}` 标记当前网络的发起者 （提供consensus component）

**Comment by 0xff-dev** [comment]
> CRD Organizaiton
> 
> * [ ]  `bestchains.organization.admin: {admin_user_name}` 标记当前组织的管理员

https://github.com/bestchains/fabric-operator/pull/50

**Comment by bjwswang** [comment]
CRD Vote
- [ ] `bestchains.vote.federation: {federation_name}` 
- [ ] `bestchains.vote.proposal: {proposal_name}`
- [ ] `bestchains.vote.proposal.type: {proposal_type}`
